POST http://localhost:10000/api/v1/doctors-appointment
Content-Type: application/json

{
    "date": "2022-01-01",
    "time":  "22:04:00",
    "place": "Example place 2",
    "attendingPhysicianId": "ff4cfc87-6652-4d4b-88b2-1bd8f2434734",
    "patientId": "ae736505-5277-45f8-8b2d-cd6c85ff615c"
}

###

GET http://localhost:10000/api/v1/doctors-appointment?patientId=182fb7cf-5032-4b37-a4c3-e8cda550b9b0

###
PUT http://localhost:10000/api/v1/doctors-appointment/98dc5e49-4c18-443f-90a3-3350346f4478
Content-Type: application/json

{
    "newTime": "15:00:00"
}

###
DELETE http://localhost:10000/api/v1/doctors-appointment/526d0e42-6f93-4815-9ba0-c2f7fbc5bd53
