POST http://localhost:10000/api/v1/patients
Content-Type: application/json

{
    "fullName": {
        "firstName": "John",
        "lastName": "Smith"
    },
    "address": {
        "city": "Poznań",
        "postcode": "61-222",
        "street": "Głogowska",
        "buildingNumber": "3",
        "apartmentNumber": null
    },
    "organizationName": "Example55"
}

###

GET http://localhost:10000/api/v1/patients

###
PUT http://localhost:10000/api/v1/patients/c537f685-6af4-4ed8-89fd-6eb53e44bcac
Content-Type: application/json

{
    "fullName": {
        "firstName": "Not John",
        "lastName": "Smith"
    },
    "address": {
        "city": "Warszawa",
        "postcode": "00-000",
        "street": "Głogowska",
        "buildingNumber": "44",
        "apartmentNumber": null
    }
}

###
DELETE http://localhost:10000/api/v1/patients/526d0e42-6f93-4815-9ba0-c2f7fbc5bd53
