POST http://localhost:10000/api/v1/patients
Content-Type: application/json

{
    "fullName": {
        "firstName": "John",
        "lastName": "Smith"
    },
    "address": {
        "city": "Poznań",
        "postcode": "61-222",
        "street": "Głogowska",
        "buildingNumber": "3",
        "apartmentNumber": null
    },
    "organizationName": "Example"
}
